//session
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SET_HEADING = "SET_HEADING";
export const SET_MENU_CALLBACK = "SET_MENU_CALLBACK";
export const SHOW_AVATAR_MENU = "SHOW_AVATAR_MENU";
export const CONTINUE_EDITING = "CONTINUE_EDITING";
export const SWITCH_UI_MODE = "SWITCH_UI_MODE";
export const SET_RETROSPECTIVE_BY_ID = "SET_RETROSPECTIVE_BY_ID";
export const SET_ACTIVE_CONTROL = "SET_ACTIVE_CONTROL";
export const SET_SELECTED_TENANT = "SET_SELECTED_TENANT";
export const ADD_TENANT = "ADD_TENANT";
export const UPDATE_TENANT = "UPDATE_TENANT";
export const REMOVE_TENANT = "REMOVE_TENANT";

//retrospectives
export const SET_RETROSPECTIVES = "SET_RETROSPECTIVES";
export const ADD_RETROSPECTIVE = "ADD_RETROSPECTIVE";
export const REMOVE_RETROSPECTIVE = "REMOVE_RETROSPECTIVE";

//retrospective
export const SET_RETROSPECTIVE = "SET_RETROSPECTIVE";
export const UPDATE_OBSERVATION = "UPDATE_OBSERVATION";
export const ADD_OBSERVATION = "ADD_OBSERVATION";
export const DELETE_OBSERVATION = "DELETE_OBSERVATION";
export const UPDATE_ACTION = "UPDATE_ACTION";
export const ADD_ACTION = "ADD_ACTION";
export const DELETE_ACTION = "DELETE_ACTION";