export const MANAGE_RETROSPECTIVES = "MANAGE_RETROSPECTIVES";
export const EDIT_RETROSPECTIVE = "EDIT_RETROSPECTIVE";
export const ADMINISTER_RETROSPECTIVE = "ADMINISTER_RETROSPECTIVE";
export const ADMINISTER_SYSTEM = "ADMINISTER_SYSTEM";
export const MANAGE_TENANTS = "MANAGE_TENANTS";